# Copyright (c) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: deviceplugin.intel.com/v1
kind: QatDevicePlugin
metadata:
  name: qatdeviceplugin-sample
spec:
  image: registry.connect.redhat.com/intel/intel-qat-plugin@sha256:12ae366fd80710f73bfc91ab7398e17101ec0fdfcad4a4e6f8e473a6c13b2b3b
  initImage: registry.connect.redhat.com/intel/intel-qat-initcontainer@sha256:c494debf7e3dc8be49ac7e634506db6892534c27f15b970954fff18310654dcb
  dpdkDriver: vfio-pci
  kernelVfDrivers:
    - 4xxxvf
  maxNumDevices: 128
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/qat: "true"