# Copyright (c) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: deviceplugin.intel.com/v1
kind: SgxDevicePlugin
metadata:
  name: sgxdeviceplugin-sample
spec:
  image: registry.connect.redhat.com/intel/intel-sgx-plugin@sha256:3cf6d2c8616915d41c0a4cf85ee46b28fb16cb6336df476802b424d48295d90f
  initImage: registry.connect.redhat.com/intel/intel-sgx-initcontainer@sha256:32f57874eb547161be985778b8b193dce1cbfebcaa0344cabb605481db9f0ab3
  enclaveLimit: 110
  provisionLimit: 110
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/sgx: "true"