# Copyright (c) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-qat
  namespace: intel-qat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: intel-qat
  namespace: intel-qat
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - intel-qat-scc
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intel-qat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: intel-qat
subjects:
- kind: ServiceAccount
  name: intel-qat
  namespace: intel-qat